---

kubernetes:
  children:
    master:
      hosts:
        apk3s00:
          ansible_host: 10.50.50.30
        apk3s01:
          ansible_host: 10.50.50.31
        apk3s02:
          ansible_host: 10.50.50.32
    
    worker:
      hosts:
        apk3s10:
          ansible_host: 10.50.50.40
        apk3s11:
          ansible_host: 10.50.50.41
        apk3s12:
          ansible_host: 10.50.50.42
        aprp01:
          ansible_host: 10.50.50.101
        aprp02:
          ansible_host: 10.50.50.102
        aprp03:
          ansible_host: 10.50.50.103
        aprp04:
          ansible_host: 10.50.50.104
        aprp05:
          ansible_host: 10.50.50.105
        aprp06:
          ansible_host: 10.50.50.106
        aprp07:
          ansible_host: 10.50.50.107
        aprp08:
          ansible_host: 10.50.50.108
        aprp09:
          ansible_host: 10.50.50.109
        aprp10:
          ansible_host: 10.50.50.110
        aprp11:
          ansible_host: 10.50.50.111
        aprp12:
          ansible_host: 10.50.50.112
        aprp13:
          ansible_host: 10.50.50.113
        aprp14:
          ansible_host: 10.50.50.114
        aprp15:
          ansible_host: 10.50.50.115
        aprp16:
          ansible_host: 10.50.50.116
        aprp17:
          ansible_host: 10.50.50.117
        aprp18:
          ansible_host: 10.50.50.118
        aprp19:
          ansible_host: 10.50.50.119

    storage:
      hosts:
        apnas01:
          ansible_host: 10.50.50.10
    # newhosts:
    #   hosts:
    #     

    rpi:
      hosts:
        aprp01:
        aprp02:
        aprp03:
        aprp04:
        aprp05:
        aprp06:
        aprp07:
        aprp08:
        aprp09:
        aprp10:
        aprp11:
        aprp12:
        aprp13:
        aprp14:
        aprp15:
        aprp16:
        aprp17:
        aprp18:
        aprp19:
    ceph:
      hosts:
        aprp01:
        aprp02:
        aprp03:
        aprp04:
        aprp05:
        aprp06:
        aprp07:
        aprp08:
        aprp09:
        aprp10:
        aprp11:
        aprp12:



workstation:
  hosts:
    nprodromou:
      ansible_host: 10.50.1.110

    nprodromou01:
      ansible_host: 10.50.1.158






